project_id = "wkvfjghgjowbcxjrzrpc"

[functions.webhook-lead]
verify_jwt = false

[functions.sync-taxas-bcb]
verify_jwt = false

[functions.instagram-sync]
verify_jwt = false

[functions.create-vendedor-user]
verify_jwt = false

[functions.delete-user]
verify_jwt = false

[functions.lead-scoring]
verify_jwt = false

[functions.test-evolution-connection]
verify_jwt = false

[functions.send-whatsapp-message]
verify_jwt = false

[functions.list-users-emails]
verify_jwt = false

[functions.process-whatsapp-automations]
verify_jwt = false
